spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 10
    initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update #自动建立表
    show-sql: true #控制台打印sql
